// 희귀도 랭크 (정렬용)
const rarityRank = { '구세나': 1, '찐스': 2, '짭스': 3, '희귀': 4 };

// 영웅 데이터
const heroData = [
    // 구세나
    { name: '로지', rarity: '구세나', role: '지원형' }, { name: '겔리두스', rarity: '구세나', role: '만능형' }, { name: '쥬리', rarity: '구세나', role: '마법형' }, { name: '밀리아', rarity: '구세나', role: '마법형' }, { name: '파이', rarity: '구세나', role: '공격형' },
    // 찐스
    { name: '델론즈', rarity: '찐스', role: '공격형' }, { name: '실베스타', rarity: '찐스', role: '마법형' }, { name: '태오', rarity: '찐스', role: '공격형' }, { name: '카일', rarity: '찐스', role: '공격형' }, { name: '스파이크', rarity: '찐스', role: '만능형' }, { name: '연희', rarity: '찐스', role: '마법형' }, { name: '루디', rarity: '찐스', role: '방어형' }, { name: '플라튼', rarity: '찐스', role: '지원형' }, { name: '크리스', rarity: '찐스', role: '만능형' }, { name: '레이첼', rarity: '찐스', role: '만능형' }, { name: '제이브', rarity: '찐스', role: '만능형' }, { name: '카르마', rarity: '찐스', role: '만능형' }, { name: '라이언', rarity: '찐스', role: '공격형' }, { name: '브란즈&브란셀', rarity: '찐스', role: '공격형' }, { name: '나타', rarity: '찐스', role: '마법형' }, { name: '트루드', rarity: '찐스', role: '만능형' }, { name: '란드그리드', rarity: '찐스', role: '공격형' }, { name: '바네사', rarity: '찐스', role: '마법형' }, { name: '린', rarity: '찐스', role: '마법형' }, { name: '아일린', rarity: '찐스', role: '만능형' }, { name: '콜트', rarity: '찐스', role: '공격형' }, { name: '카구라', rarity: '찐스', role: '공격형' }, { name: '라드그리드', rarity: '찐스', role: '방어형' }, { name: '비스킷', rarity: '찐스', role: '지원형' }, { name: '여포', rarity: '찐스', role: '공격형' }, { name: '프레이야', rarity: '찐스', role: '마법형' }, { name: '레긴레이프', rarity: '찐스', role: '마법형' }, { name: '성진우', rarity: '찐스', role: '마법형' }, { name: '오목', rarity: '찐스', role: '마법형' }, { name: '에이스', rarity: '찐스', role: '만능형' }, { name: '엘리시아', rarity: '찐스', role: '만능형' }, { name: '팔라누스', rarity: '찐스', role: '만능형' }, { name: '손오공', rarity: '찐스', role: '만능형' }, { name: '미스트', rarity: '찐스', role: '만능형' }, { name: '멜키르', rarity: '찐스', role: '마법형' }, { name: '아킬라', rarity: '찐스', role: '방어형' }, { name: '오를리', rarity: '찐스', role: '지원형' }, { name: '클라한', rarity: '찐스', role: '공격형' }, { name: '칼 헤론', rarity: '찐스', role: '공격형' }, { name: '스쿨드', rarity: '찐스', role: '마법형' }, { name: '클레미스', rarity: '찐스', role: '지원형' }, { name: '키리엘', rarity: '찐스', role: '마법형' },
    // 짭스
    { name: '돼오', rarity: '짭스', role: '공격형' }, { name: '비담', rarity: '짭스', role: '공격형' }, { name: '세인', rarity: '짭스', role: '공격형' }, { name: '아멜리아', rarity: '짭스', role: '공격형' }, { name: '백룡', rarity: '짭스', role: '공격형' }, { name: '벨리카', rarity: '짭스', role: '마법형' }, { name: '루리', rarity: '짭스', role: '마법형' }, { name: '에스파다', rarity: '짭스', role: '마법형' }, { name: '파스칼', rarity: '짭스', role: '마법형' }, { name: '소교', rarity: '짭스', role: '마법형' }, { name: '녹스', rarity: '짭스', role: '방어형' }, { name: '리나', rarity: '짭스', role: '지원형' }, { name: '니아', rarity: '짭스', role: '만능형' }, { name: '유신', rarity: '짭스', role: '마법형' }, { name: '룩', rarity: '짭스', role: '방어형' }, { name: '엘리스', rarity: '짭스', role: '지원형' }, { name: '타카', rarity: '짭스', role: '공격형' }, { name: '초선', rarity: '짭스', role: '지원형' }, { name: '지크', rarity: '짭스', role: '만능형' }, { name: '챈슬러', rarity: '짭스', role: '만능형' }, { name: '백각', rarity: '짭스', role: '만능형' }, { name: '관우', rarity: '짭스', role: '만능형' }, { name: '데이지', rarity: '짭스', role: '마법형' }, { name: '미호', rarity: '짭스', role: '마법형' }, { name: '발리스타', rarity: '짭스', role: '공격형' }, { name: '아라곤', rarity: '짭스', role: '방어형' }, { name: '차해인', rarity: '짭스', role: '공격형' },
    // 희귀 (유진호, 이주희 추가됨)
    { name: '샤오', rarity: '희귀', role: '공격형' }, { name: '링링', rarity: '희귀', role: '마법형' }, { name: '조운', rarity: '희귀', role: '공격형' }, { name: '레이', rarity: '희귀', role: '공격형' }, { name: '진', rarity: '희귀', role: '공격형' }, { name: '캐티', rarity: '희귀', role: '공격형' }, { name: '블랙로즈', rarity: '희귀', role: '공격형' }, { name: '아수라', rarity: '희귀', role: '만능형' }, { name: '노호', rarity: '희귀', role: '마법형' }, { name: '클로에', rarity: '희귀', role: '지원형' }, { name: '메이', rarity: '희귀', role: '공격형' }, { name: '세라', rarity: '희귀', role: '마법형' }, { name: '제인', rarity: '희귀', role: '공격형' }, { name: '유이', rarity: '희귀', role: '지원형' }, { name: '실비아', rarity: '희귀', role: '마법형' }, { name: '루시', rarity: '희귀', role: '지원형' }, { name: '빅토리아', rarity: '희귀', role: '만능형' }, { name: '카론', rarity: '희귀', role: '지원형' }, { name: '조커', rarity: '희귀', role: '마법형' }, { name: '카린', rarity: '희귀', role: '지원형' }, { name: '에반', rarity: '희귀', role: '방어형' }, { name: '쥬피', rarity: '희귀', role: '공격형' }, { name: '스니퍼', rarity: '희귀', role: '공격형' }, { name: '소이', rarity: '희귀', role: '공격형' }, { name: '풍연', rarity: '희귀', role: '공격형' }, { name: '헤브니아', rarity: '희귀', role: '공격형' }, { name: '헬레니아', rarity: '희귀', role: '방어형' }, { name: '아리엘', rarity: '희귀', role: '마법형' }, { name: '리', rarity: '희귀', role: '방어형' }, { name: '사라', rarity: '희귀', role: '지원형' }, { name: '라니아', rarity: '희귀', role: '만능형' }, { name: '클레오', rarity: '희귀', role: '마법형' }, { name: '베인', rarity: '희귀', role: '마법형' }, { name: '레오', rarity: '희귀', role: '공격형' }, { name: '유리', rarity: '희귀', role: '마법형' }, { name: '라쿤', rarity: '희귀', role: '방어형' }, { name: '호킨', rarity: '희귀', role: '공격형' }, { name: '유진호', rarity: '희귀', role: '방어형' }, { name: '이주희', rarity: '희귀', role: '지원형' }
];

// 펫 데이터
const petData = [
    { name: '더지' }, { name: '델로' }, { name: '루' }, { name: '리첼' }, { name: '맬페로' }, { name: '믹' }, { name: '에리' }, { name: '연지' }, { name: '윈디' }, { name: '유' }, { name: '이린' }, { name: '카람' }, { name: '크리' }, { name: '파이크' }, { name: '제오' }, { name: '요랑' }, { name: '제브' }
];